language: php
sudo: false

php:
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - mysql -e 'CREATE DATABASE `med-union-user-plateform`;'
  - cp .env.travis .env
  - pecl install mongodb
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - php artisan migrate

script:
  - phpunit


notifications:
  slack:
    rooms:
      - whplay:zU0w0tRPIdeLYyKaXsHXDHPI#med-user-plateform