language: php

php:
  - '5.6'
  - '7.0'
  - 'nightly'


cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mysql -e 'CREATE DATABASE `med-union-user-plateform`;'
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - php artisan migrate

script: phpunit

services:
  - mysql

notifications:
  slack:
    rooms:
      - whplay:zU0w0tRPIdeLYyKaXsHXDHPI#med-user-plateform