language: php
sudo: false

php:
  - '5.6'
  - '7.0'

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - mysql -e 'CREATE DATABASE `med-union-user-plateform`;'
  - cp .env.travis .env
  - if [[ $TRAVIS_PHP_VERSION >= 7.0 ]] ; then phpenv config-rm xdebug.ini; fi
  - if [[ $TRAVIS_PHP_VERSION >= 7.0 ]] ; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
; fi
  - if [[ $TRAVIS_PHP_VERSION <= 5.6 ]] ; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
; fi
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - php artisan migrate

script:
  - if [[ $TRAVIS_PHP_VERSION == 7.0 ]] ; then phpdbg -qrr phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION == 5.6 ]] ; then phpunit; fi


notifications:
  slack:
    rooms:
      - whplay:zU0w0tRPIdeLYyKaXsHXDHPI#med-user-plateform